- nodeset:
    name: emea
    nodes:
      - name: node_emea
        label: centos76
    groups:
      - name: emea
        nodes:
          - node_emea

- job:
    name: check_location
    run: playbooks/check_location.yaml
    parent: base

- job:
    name: pullrequest_label
    run: playbooks/pullrequest_label.yaml
    dependencies:
      - check_location
    parent: base

          
- project:
    pullrequest_label:
      jobs:
        - check_location
        - pullrequest_label
             nodeset: emea
