- nodeset:
    name: emea
    nodes:
      - name: node_emea
        label: centos76
    groups:
      - name: emea
        nodes:
          - node_emea

- job:
    name: check_location
    run: playbooks/check_location.yaml
    voting: false
    parent: base

- job:
    name: pullrequest_label
    run: playbooks/pullrequest_label.yaml
    dependencies:
      - check_location
    parent: base
    nodeset: emea

          
- project:
    pullrequest_label:
      jobs:
        - check_location
        - pullrequest_label
